### ISSUE TITLE
Missing styled-scrollbar scss mixin

### ISSUE THREAD

**Issue by timoransky** [grrr-amsterdam/cookie-consent#11]
Hi, I was to about to try this package, but upon building my assets, it failed on undefined mixin error at line 7 in your scss file. Can you maybe provide mentioned mixin or remove the line?
```
ERROR in ./resources/sass/frontend/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
  ╷
7 │     @include styled-scrollbar;
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
````

**Comment by harmenjanssen** [comment]
Thanks for alerting us to this issue! 
I've fixed it: this mixin was in another repo. I've moved the contained styles over to the stylesheet in this repo.

The new version `1.0.3` will contain the fix.
