### ISSUE TITLE
Checkbox returns to true after being unchecked

### ISSUE THREAD

**Issue by dschi** [grrr-amsterdam/cookie-consent#16]
Hi,

```
const requiredCount = config.get('cookies').filter(c => c.required).length;
    const checkedCount = values.filter(v => v.accepted).length;
    const userOptionsChecked = checkedCount > requiredCount;
    if (ACCEPT_ALL_BUTTON && TYPE === 'checkbox' && !userOptionsChecked) {
      return values.map(value => ({
        ...value,
        accepted: true,
      }));
    }
```

If you have one setting required and one optional and uncheck the optional, this will compare 1 > 1 leading to re-check the optional.
I think `checkedCount >= requiredCount` would fix it.

**Comment by qmeister** [comment]
Hi @dschi,

Thank you for your feedback and suggestion! If no cookie-settings have been saved yet, in which case `ACCEPT_ALL_BUTTON ` has been set to true, the optional checkbox will be checked in any case indeed. Your suggestion seems to be a good fix. See the linked PR, which will be reviewed.

Thank you,
Jochem
