### ISSUE TITLE
Callback option?

### ISSUE THREAD

**Issue by appel** [grrr-amsterdam/cookie-consent#18]
Hey there, thanks so much for this amazing script, it works like a charm! I looked at the docs, but couldn't find it: is there a callback option?

I would love to be able to record whether people accept or reject cookies, it would help explain to my client why his e-commerce analytics are incomplete. :)

**Comment by martijngastkemper** [comment]
Maybe you can use the `update` event ([See docs](https://github.com/grrr-amsterdam/cookie-consent#events))? When that's not sufficient you can create a pull request to add the feature.

**Comment by appel** [comment]
Oops, no idea how I overlooked that, apologies! Seems like that's exactly what I needed. Thanks again!
