### ISSUE TITLE
Hide the cookie notice when in print mode

### ISSUE THREAD

**Issue by JairoTheDev** [grrr-amsterdam/cookie-consent#31]
The cookie notice is still shown when you are in print mode. It would be nice to instead hide the cookie notice or have an option to control it.

![Screenshot 2024-01-15 at 10 28 31](https://github.com/grrr-amsterdam/cookie-consent/assets/141034109/73561e53-0b3c-4db2-ba42-34128650ff67)

**Comment by roelandvs** [comment]
Closed by #32 and #33
