### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by salisdemos** [grrr-amsterdam/cookie-consent#7]
Can You please proveide a License, that Github can show the type of License?
You just can copy-paste the text provided here:
https://choosealicense.com/licenses/mit/

and adjust with your personal data.

Thank You for the nice project.

**Comment by martijngastkemper** [comment]
Thanks for your question. I'll ask my colleagues which license we are going to use.

**Comment by martijngastkemper** [comment]
I've added the MIT license #8
